# Generated by Django 4.0.1 on 2022-02-01 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.IntegerField(unique=True, verbose_name='شماره دانشجویی')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='ایمیل')),
                ('first_name', models.CharField(blank=True, max_length=255, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, max_length=255, verbose_name='نام خانوادگی')),
                ('city', models.CharField(blank=True, max_length=255, verbose_name='شهر')),
                ('state', models.CharField(blank=True, max_length=255, verbose_name='استان')),
                ('field', models.CharField(blank=True, max_length=255, verbose_name='')),
                ('university', models.CharField(blank=True, max_length=255, verbose_name='دانشگاه')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='%Y/%m/%d', verbose_name='تصویر پروفایل')),
                ('is_master', models.BooleanField(default=False)),
                ('is_student', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
